In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [2]:
X = np.array([-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0], dtype=float)
Y = np.array([5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0], dtype=float)

In [3]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[1])
    ])

c:\Users\Pongo\Documents\Python\Pengembangan Machine Learning\envsaya\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [5]:
model.fit(X, Y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 356ms/step - loss: 78.7464
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 75.6456
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 72.6901
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 69.8660
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 67.1626
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 64.5713
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 62.0853
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 59.6985
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 57.4059
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 55.2031
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 53.0860
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 51.0509
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 49.0943
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 47.2131
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 45.4042
Epo

In [6]:
model.predict(np.array([4, 5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step


array([[12.99962 ],
       [13.999655]], dtype=float32)

In [7]:
model.predict(np.array([4, 5])).round()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[13.],
       [14.]], dtype=float32)

In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=20, input_shape=[1]),
    tf.keras.layers.Dense(units=15),
    tf.keras.layers.Dense(units=10),
    tf.keras.layers.Dense(units=1)
    ])

In [10]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [11]:
model.fit(X, Y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - loss: 102.8385
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 109.3121
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 81.5538
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 62.6247
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 48.1087
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 33.9379
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 20.0069
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 8.0993
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 4.8194
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 41.1492
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 43.4746
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 82.3681
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 46.9048
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 30.2896
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 11.5238
Epo

In [12]:
model.predict(np.array([4, 5]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[12.999999],
       [13.999999]], dtype=float32)